# Generated by Django 5.2.7 on 2026-03-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
